eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://winhost:8761/eureka
  instance:
    hostname: winhost
    
mircroservices:
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/placeOrder

  payment-service:
    endpoints:
      endpoint:
        uri: http//PAYMENT-SERVICE/payment/doPayment
